// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_VisibilityRange","status":true,"description":"(v.1.2) Use an image to display a visibility range image around the player's position","parameters":{"Zoom Variable":"1","Opacity Variable":"2","Z Position":"10"}}
];
