// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_VisibilityRange","status":true,"description":"(v.1.2) Use an image to display a visibility range image around the player's position","parameters":{"Zoom Variable":"1","Opacity Variable":"2","Z Position":"10"}},
{"name":"GALV_EventSpawner","status":true,"description":"(v.1.7) Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"2"}}
];
